export GIT_SSH=plink
alias ll='ls -altr'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit -m '
alias gd='git diff'
alias mcp='clear && echo "mvn clean package" && mvn clean package'
alias mct='clear && echo "mvn clean test" && mvn clean test'
alias mcd='clear && echo "mvn clean deploy" && mvn clean deploy'
alias mp='clear && echo "mvn package" && mvn package'
alias mci='clear && echo "mvn clean install" && mvn clean install'
alias e.='explorer .'

export GROOVY_SCRIPT_HOME='/h/apps/scripts/'
alias g='groovy /h/apps/scripts/g.groovy'
alias deploy='g d *.war jap4'

alias tcup='/d/apps/jboss-ews-2.0/tomcat7/bin/startup.sh'
alias tcdown='/d/apps/jboss-ews-2.0/tomcat7/bin/shutdown.sh'
alias tcclean='rm /d/apps/jboss-ews-2.0/tomcat7/logs/*'
