#!/bin/bash

echo "Fixing DNS issue in WSL / Ubuntu"

echo "  - deleting /etc/resolv.conf"
sudo rm /etc/resolv.conf

echo "  - creating /etc/resolv.conf"
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'

echo "done"
